/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import db.Arquivos;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileReader;
import java.io.IOException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Map;
import java.util.Scanner;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import marcarconsulta.Consulta;

import pessoas.Medico;
import pessoas.Atendente;
import pessoas.Paciente;

/**
 *
 * @author gss21
 */
public class LoginForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    static ArrayList<Medico> medicosDb = new ArrayList();
    static ArrayList<Atendente> atendentesDb = new ArrayList();
    static ArrayList<Paciente> pacientesDb = new ArrayList();
    
    // para controle de acesso
    static Medico medicoLogado;
    static Atendente atendenteLogado;
    
    private ArrayList<String> horariosFormatados = new ArrayList();
        
    public Medico adicionarNaAgenda(Consulta consulta, Medico medico){
        
        String data = consulta.getDataHorario().toLocalDate().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")).toString();
        String hora = consulta.getDataHorario().toLocalTime().format(DateTimeFormatter.ofPattern("HH:mm")).toString();
        
        Map<String,String> agenda = medico.getAgenda();
        if(!medico.getAgenda().containsKey(data)) {
                agenda.put(data, "000000000000");
        } 
        
        StringBuilder horarios = new StringBuilder(medico.getAgenda().get(data).toString());
        horarios.setCharAt(horariosFormatados.indexOf(hora), '1');
        agenda.put(data, horarios.toString());
        medico.setAgenda(agenda);
        return medico;
    }
    
    public void importData(){
        // puxando os dados ja cadastrados
        Arquivos arquivos = new Arquivos();
        ArrayList<Paciente> pac = arquivos.carregaPaciente();
        
        // Caso não seja a primeira sessão, limpa os vetores
        pacientesDb.clear();
        atendentesDb.clear();
        medicosDb.clear();
        
        if(pac != null){
            LoginForm.pacientesDb.addAll(pac);
        }
        ArrayList<Medico> med = arquivos.carregaMedico();
        if(med != null){
            LoginForm.medicosDb.addAll(med);
        }
        ArrayList<Atendente> atende = arquivos.carregaAtendente();
        if(atende != null){
            LoginForm.atendentesDb.addAll(atende);
        }
        ArrayList<Consulta> consultas = arquivos.carregaConsulta();
        if(consultas != null){
            for(Consulta consulta: consultas){
                Paciente pacienteAux = pacientesDb.get(consulta.getIdPaciente());
                Medico medicoAux = medicosDb.get(consulta.getIdMedico());
                consulta.setMedico(medicoAux);
                consulta.setPaciente(pacienteAux);
                pacienteAux.addConsulta(consulta);
                medicoAux.addConsulta(consulta);
                medicoAux = adicionarNaAgenda(consulta, medicoAux);
                medicosDb.set(consulta.getIdMedico(), medicoAux);
                pacientesDb.set(consulta.getIdPaciente(), pacienteAux);
            }
        }
        arquivos.close();
    } 
    
    public void initHour(){
        horariosFormatados.add("07:00");
        horariosFormatados.add("08:00");
        horariosFormatados.add("09:00");
        horariosFormatados.add("10:00");
        horariosFormatados.add("11:00");
        horariosFormatados.add("13:00");
        horariosFormatados.add("14:00");
        horariosFormatados.add("15:00");
        horariosFormatados.add("16:00");
        horariosFormatados.add("17:00");
        horariosFormatados.add("18:00");
        horariosFormatados.add("19:00");
    }
    
    public LoginForm() {
        initHour();
        initComponents();
        this.setLocationRelativeTo(null);
        importData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CloseLbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        MinimizeLbl = new javax.swing.JLabel();
        logoLbl = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        usuarioTextField = new javax.swing.JTextField();
        passwordTextField = new javax.swing.JPasswordField();
        loginBnt = new javax.swing.JButton();
        CriarContaLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(34, 167, 240));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        CloseLbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        CloseLbl.setForeground(new java.awt.Color(255, 255, 255));
        CloseLbl.setText("X");
        CloseLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseLblMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Bem-vindo ao SIGAC");

        MinimizeLbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        MinimizeLbl.setForeground(new java.awt.Color(255, 255, 255));
        MinimizeLbl.setText("-");
        MinimizeLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizeLblMouseClicked(evt);
            }
        });

        logoLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(logoLbl)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MinimizeLbl)
                .addGap(18, 18, 18)
                .addComponent(CloseLbl)
                .addGap(35, 35, 35))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logoLbl)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CloseLbl)
                        .addComponent(MinimizeLbl)
                        .addComponent(jLabel2)))
                .addGap(9, 9, 9))
        );

        jPanel2.setBackground(new java.awt.Color(102, 51, 153));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel4.setBackground(new java.awt.Color(236, 240, 241));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(236, 240, 241));
        jLabel4.setText("Usuário:");

        jLabel5.setBackground(new java.awt.Color(236, 240, 241));
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(236, 240, 241));
        jLabel5.setText("Senha:");

        usuarioTextField.setBackground(new java.awt.Color(108, 122, 137));
        usuarioTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        usuarioTextField.setForeground(new java.awt.Color(228, 241, 254));
        usuarioTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioTextFieldActionPerformed(evt);
            }
        });

        passwordTextField.setBackground(new java.awt.Color(108, 122, 137));
        passwordTextField.setForeground(new java.awt.Color(255, 255, 255));
        passwordTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTextFieldActionPerformed(evt);
            }
        });
        passwordTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordTextFieldKeyPressed(evt);
            }
        });

        loginBnt.setBackground(new java.awt.Color(34, 167, 240));
        loginBnt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        loginBnt.setForeground(new java.awt.Color(255, 255, 255));
        loginBnt.setText("Login");
        loginBnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBntActionPerformed(evt);
            }
        });
        loginBnt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                loginBntKeyPressed(evt);
            }
        });

        CriarContaLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CriarContaLbl.setForeground(new java.awt.Color(255, 255, 255));
        CriarContaLbl.setText("Clique para criar uma nova conta");
        CriarContaLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CriarContaLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CriarContaLblMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CriarContaLbl)
                    .addComponent(loginBnt)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(usuarioTextField)
                            .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(usuarioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(loginBnt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CriarContaLbl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usuarioTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioTextFieldActionPerformed

    private void passwordTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordTextFieldActionPerformed

    private void CloseLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseLblMouseClicked
       System.exit(0);
    }//GEN-LAST:event_CloseLblMouseClicked

    private void MinimizeLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeLblMouseClicked
       this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_MinimizeLblMouseClicked

    private void loginBntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBntActionPerformed
        for (int i = 0; i < medicosDb.size(); i++){
            if (medicosDb.get(i).getEmail().equals(usuarioTextField.getText())){
              if (medicosDb.get(i).getSenha().equals(passwordTextField.getText())){
                    medicoLogado = medicosDb.get(i);
                                      
                    PrincipalMedico md = new PrincipalMedico();
                    md.setVisible(true);
                    md.pack();
                    //md.setLocationRelativeTo(null);
                    md.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                    md.setLocationRelativeTo(null);
                    this.dispose();
                    return;
                }
                else {
                    JOptionPane.showMessageDialog(null, "Senha errada", "Erro", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
        } 
        
        for (int i = 0; i < atendentesDb.size(); i++){
            if (atendentesDb.get(i).getEmail().equals(usuarioTextField.getText().trim())){
              if (atendentesDb.get(i).getSenha().equals(passwordTextField.getText().trim())){  
                    atendenteLogado = atendentesDb.get(i);
                    
                    PrincipalAtendente at = new PrincipalAtendente();
                    at.setVisible(true);
                    at.pack();
                    at.setLocationRelativeTo(null);
                    at.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                    this.dispose();
                    return;
                }
                else {
                    JOptionPane.showMessageDialog(null, "Senha errada", "Erro", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
        }
        JOptionPane.showMessageDialog(null, "Usuario não encontrado!", "Erro", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_loginBntActionPerformed

    private void CriarContaLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CriarContaLblMouseClicked
       RegisterForm rgf = new RegisterForm();
       rgf.setVisible(true);
       rgf.pack();
       rgf.setLocationRelativeTo(null);
       rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
       
    }//GEN-LAST:event_CriarContaLblMouseClicked

    private void loginBntKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_loginBntKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBntKeyPressed

    private void passwordTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordTextFieldKeyPressed
    }//GEN-LAST:event_passwordTextFieldKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CloseLbl;
    private javax.swing.JLabel CriarContaLbl;
    private javax.swing.JLabel MinimizeLbl;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton loginBnt;
    private javax.swing.JLabel logoLbl;
    private javax.swing.JPasswordField passwordTextField;
    private javax.swing.JTextField usuarioTextField;
    // End of variables declaration//GEN-END:variables
}
