/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import db.Arquivos;
import features.SendEmail;
import helpers.ValidacaoCPF;
import javax.swing.JFrame;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;
import pessoas.Atendente;
import pessoas.Medico;

/**
 *
 * @author gss21
 */
public class RegisterForm extends javax.swing.JFrame {
    

     public static void WriteFile(String caminho, String texto){
        try (
            FileWriter criaArquivo = new FileWriter(caminho, true);
            BufferedWriter buffer = new BufferedWriter(criaArquivo);
            PrintWriter escrever = new PrintWriter (buffer);
                  ){
             escrever.append(texto);
                
        } catch(IOException e){
            System.out.println(e.getMessage());
        }
    }
       
    public RegisterForm() {
        initComponents();
      
        this.setLocationRelativeTo(null);
        
        crmLbl.setVisible(false);
        crmTxtField.setVisible(false);
        especialidadeLbl.setVisible(false);
        especialidadeTxtField.setVisible(false);
        nBalcaoLbl.setVisible(false);
        nBalcaoTxtField.setVisible(false);
        
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CloseLbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        MinimizeLbl = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        nomeLbl = new javax.swing.JLabel();
        nomeTxtField = new javax.swing.JTextField();
        cpfLbl = new javax.swing.JLabel();
        sexoLbl = new javax.swing.JLabel();
        sexoCombo = new javax.swing.JComboBox<>();
        endereçoLbl = new javax.swing.JLabel();
        endereçoTxtField = new javax.swing.JTextField();
        emailLbl1 = new javax.swing.JLabel();
        emailTxtField = new javax.swing.JTextField();
        celularLbl = new javax.swing.JLabel();
        celularTxtField = new javax.swing.JFormattedTextField();
        dataDeNascimentoLbl = new javax.swing.JLabel();
        dataNascimentoTxtField = new javax.swing.JFormattedTextField();
        senhaLbl = new javax.swing.JLabel();
        senhaField = new javax.swing.JPasswordField();
        tipoDeContaLbl = new javax.swing.JLabel();
        cancelarBnt = new javax.swing.JButton();
        criarContaBnt = new javax.swing.JButton();
        tipoContaCombo = new javax.swing.JComboBox<>();
        crmLbl = new javax.swing.JLabel();
        crmTxtField = new javax.swing.JTextField();
        especialidadeLbl = new javax.swing.JLabel();
        especialidadeTxtField = new javax.swing.JTextField();
        nBalcaoLbl = new javax.swing.JLabel();
        nBalcaoTxtField = new javax.swing.JTextField();
        cpfTxtField1 = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(643, 597));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(34, 167, 240));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        CloseLbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        CloseLbl.setForeground(new java.awt.Color(255, 255, 255));
        CloseLbl.setText("X");
        CloseLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseLblMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Criação de Conta");

        MinimizeLbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        MinimizeLbl.setForeground(new java.awt.Color(255, 255, 255));
        MinimizeLbl.setText("-");
        MinimizeLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizeLblMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MinimizeLbl)
                .addGap(18, 18, 18)
                .addComponent(CloseLbl)
                .addGap(35, 35, 35))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CloseLbl)
                    .addComponent(MinimizeLbl)
                    .addComponent(jLabel2))
                .addGap(9, 9, 9))
        );

        jPanel2.setBackground(new java.awt.Color(102, 51, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        nomeLbl.setBackground(new java.awt.Color(236, 240, 241));
        nomeLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nomeLbl.setForeground(new java.awt.Color(236, 240, 241));
        nomeLbl.setText("Nome:");

        nomeTxtField.setBackground(new java.awt.Color(108, 122, 137));
        nomeTxtField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nomeTxtField.setForeground(new java.awt.Color(228, 241, 254));
        nomeTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeTxtFieldActionPerformed(evt);
            }
        });

        cpfLbl.setBackground(new java.awt.Color(236, 240, 241));
        cpfLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cpfLbl.setForeground(new java.awt.Color(236, 240, 241));
        cpfLbl.setText("CPF:");

        sexoLbl.setBackground(new java.awt.Color(236, 240, 241));
        sexoLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sexoLbl.setForeground(new java.awt.Color(236, 240, 241));
        sexoLbl.setText("Sexo:");

        sexoCombo.setBackground(new java.awt.Color(34, 167, 240));
        sexoCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino", "Outro" }));

        endereçoLbl.setBackground(new java.awt.Color(236, 240, 241));
        endereçoLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        endereçoLbl.setForeground(new java.awt.Color(236, 240, 241));
        endereçoLbl.setText("Endereço:");

        endereçoTxtField.setBackground(new java.awt.Color(108, 122, 137));
        endereçoTxtField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        endereçoTxtField.setForeground(new java.awt.Color(228, 241, 254));
        endereçoTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endereçoTxtFieldActionPerformed(evt);
            }
        });

        emailLbl1.setBackground(new java.awt.Color(236, 240, 241));
        emailLbl1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        emailLbl1.setForeground(new java.awt.Color(236, 240, 241));
        emailLbl1.setText("Email:");

        emailTxtField.setBackground(new java.awt.Color(108, 122, 137));
        emailTxtField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        emailTxtField.setForeground(new java.awt.Color(228, 241, 254));
        emailTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTxtFieldActionPerformed(evt);
            }
        });

        celularLbl.setBackground(new java.awt.Color(236, 240, 241));
        celularLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        celularLbl.setForeground(new java.awt.Color(236, 240, 241));
        celularLbl.setText("Celular:");

        celularTxtField.setBackground(new java.awt.Color(108, 122, 137));
        celularTxtField.setForeground(new java.awt.Color(236, 240, 241));
        try {
            celularTxtField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)9 ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        dataDeNascimentoLbl.setBackground(new java.awt.Color(236, 240, 241));
        dataDeNascimentoLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dataDeNascimentoLbl.setForeground(new java.awt.Color(236, 240, 241));
        dataDeNascimentoLbl.setText("Data de Nascimento:");

        dataNascimentoTxtField.setBackground(new java.awt.Color(108, 122, 137));
        dataNascimentoTxtField.setForeground(new java.awt.Color(228, 241, 254));
        try {
            dataNascimentoTxtField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        dataNascimentoTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataNascimentoTxtFieldActionPerformed(evt);
            }
        });

        senhaLbl.setBackground(new java.awt.Color(236, 240, 241));
        senhaLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        senhaLbl.setForeground(new java.awt.Color(236, 240, 241));
        senhaLbl.setText("Senha:");

        senhaField.setBackground(new java.awt.Color(108, 122, 137));
        senhaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaFieldActionPerformed(evt);
            }
        });

        tipoDeContaLbl.setBackground(new java.awt.Color(236, 240, 241));
        tipoDeContaLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tipoDeContaLbl.setForeground(new java.awt.Color(236, 240, 241));
        tipoDeContaLbl.setText("Tipo de Conta:");

        cancelarBnt.setBackground(new java.awt.Color(242, 38, 19));
        cancelarBnt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cancelarBnt.setForeground(new java.awt.Color(255, 255, 255));
        cancelarBnt.setText("Cancelar");
        cancelarBnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBntActionPerformed(evt);
            }
        });

        criarContaBnt.setBackground(new java.awt.Color(34, 167, 240));
        criarContaBnt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        criarContaBnt.setForeground(new java.awt.Color(255, 255, 255));
        criarContaBnt.setText("Criar conta");
        criarContaBnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criarContaBntActionPerformed(evt);
            }
        });

        tipoContaCombo.setBackground(new java.awt.Color(34, 167, 240));
        tipoContaCombo.setForeground(new java.awt.Color(108, 122, 137));
        tipoContaCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Médico", "Atendente" }));
        tipoContaCombo.setSelectedIndex(-1);
        tipoContaCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoContaComboActionPerformed(evt);
            }
        });

        crmLbl.setBackground(new java.awt.Color(236, 240, 241));
        crmLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        crmLbl.setForeground(new java.awt.Color(236, 240, 241));
        crmLbl.setText("CRM:");

        crmTxtField.setBackground(new java.awt.Color(108, 122, 137));
        crmTxtField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        crmTxtField.setForeground(new java.awt.Color(228, 241, 254));
        crmTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crmTxtFieldActionPerformed(evt);
            }
        });

        especialidadeLbl.setBackground(new java.awt.Color(236, 240, 241));
        especialidadeLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        especialidadeLbl.setForeground(new java.awt.Color(236, 240, 241));
        especialidadeLbl.setText("Especialidade:");

        especialidadeTxtField.setBackground(new java.awt.Color(108, 122, 137));
        especialidadeTxtField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        especialidadeTxtField.setForeground(new java.awt.Color(228, 241, 254));
        especialidadeTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                especialidadeTxtFieldActionPerformed(evt);
            }
        });

        nBalcaoLbl.setBackground(new java.awt.Color(236, 240, 241));
        nBalcaoLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nBalcaoLbl.setForeground(new java.awt.Color(236, 240, 241));
        nBalcaoLbl.setText("Nº do balcão:");

        nBalcaoTxtField.setBackground(new java.awt.Color(108, 122, 137));
        nBalcaoTxtField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nBalcaoTxtField.setForeground(new java.awt.Color(228, 241, 254));
        nBalcaoTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nBalcaoTxtFieldActionPerformed(evt);
            }
        });

        cpfTxtField1.setBackground(new java.awt.Color(108, 122, 137));
        cpfTxtField1.setForeground(new java.awt.Color(228, 241, 254));
        try {
            cpfTxtField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cpfTxtField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfTxtField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(tipoDeContaLbl)
                        .addGap(18, 18, 18)
                        .addComponent(tipoContaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(endereçoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(endereçoTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(dataDeNascimentoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dataNascimentoTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(senhaLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(senhaField, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(cancelarBnt)
                        .addGap(62, 62, 62)
                        .addComponent(criarContaBnt))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(emailLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(celularLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(celularTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(sexoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(cpfLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(190, 190, 190)
                                .addComponent(especialidadeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(especialidadeTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(sexoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(nomeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cpfTxtField1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(nomeTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(crmLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(nBalcaoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(2, 2, 2)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(crmTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(nBalcaoTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoDeContaLbl)
                    .addComponent(tipoContaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomeLbl)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(nomeTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(crmLbl)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(nBalcaoLbl))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(crmTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(nBalcaoTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cpfLbl)
                        .addComponent(cpfTxtField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(especialidadeLbl))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(especialidadeTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sexoLbl)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(sexoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(endereçoLbl)
                    .addComponent(endereçoTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(emailLbl1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(emailTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(celularLbl)
                    .addComponent(celularTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataDeNascimentoLbl)
                    .addComponent(dataNascimentoTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(senhaLbl)
                    .addComponent(senhaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cancelarBnt)
                    .addComponent(criarContaBnt))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeTxtFieldActionPerformed

    private void cancelarBntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBntActionPerformed
       LoginForm rgf = new LoginForm();
       rgf.setVisible(true);
       rgf.pack();
       rgf.setLocationRelativeTo(null);
       rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
       this.dispose();
    }//GEN-LAST:event_cancelarBntActionPerformed

    private void endereçoTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endereçoTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_endereçoTxtFieldActionPerformed

    private void emailTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTxtFieldActionPerformed

    private void criarContaBntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criarContaBntActionPerformed
        String tipoConta;
        if (tipoContaCombo.getSelectedIndex() != -1)
             tipoConta = tipoContaCombo.getSelectedItem().toString();
        
        Arquivos arquivo = new Arquivos();
        
        String nome = nomeTxtField.getText().trim();        
        String cpf = cpfTxtField1.getText().trim();
        String sexo = sexoCombo.getSelectedItem().toString().trim();
        String endereço = endereçoTxtField.getText().trim();
        String email = emailTxtField.getText().trim();
        String celular = celularTxtField.getText().trim();
        String dataNascimento = dataNascimentoTxtField.getText().trim();
        String senha = String.copyValueOf((senhaField.getPassword())).trim();
        String crm = crmTxtField.getText().trim();
        String especialidade = especialidadeTxtField.getText().trim();
        String nBalcao = nBalcaoTxtField.getText().trim();
        LocalDate date = null;
        try{
            date = LocalDate.parse(dataNascimento, DateTimeFormatter.ofPattern("dd/MM/yyyy"));
        }catch(DateTimeParseException io){
            JOptionPane.showMessageDialog(null, "A data é inválida", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (nome.isEmpty())
            JOptionPane.showMessageDialog(null, "O campo nome não pode ser vazio", "Erro", JOptionPane.ERROR_MESSAGE);
        else if(!ValidacaoCPF.isValidCPF(cpf.substring(0, 3)+cpf.substring(4, 7)+cpf.substring(8, 11)+cpf.substring(12, 14))) {
            System.out.println(cpf.substring(0, 3)+cpf.substring(4, 7)+cpf.substring(8, 11)+cpf.substring(12, 14));
            JOptionPane.showMessageDialog(null, "O CPF informado é inválido", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        else if (email.isEmpty())
            JOptionPane.showMessageDialog(null, "O campo email não pode ser vazio", "Erro", JOptionPane.ERROR_MESSAGE);
        else if (endereço.isEmpty())
            JOptionPane.showMessageDialog(null, "O campo endereço não pode ser vazio", "Erro", JOptionPane.ERROR_MESSAGE);
        else if (celular.isEmpty())
            JOptionPane.showMessageDialog(null, "O campo celular não pode ser vazio", "Erro", JOptionPane.ERROR_MESSAGE);
        else if (senha.isEmpty())
            JOptionPane.showMessageDialog(null, "Crie uma senha para a conta", "Erro", JOptionPane.ERROR_MESSAGE);
        else if (!SendEmail.verifyEmail(email)){
            return;
        } else {
            if (tipoContaCombo.getSelectedIndex() == 0){
                if (crm.isEmpty()){
                    JOptionPane.showMessageDialog(null, "O campo CRM não pode ser vazio", "Erro", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                else if (especialidade.isEmpty()){
                    JOptionPane.showMessageDialog(null, "O campo especialidade não pode ser vazio", "Erro", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                Medico medico = new Medico(nome,cpf,sexo,endereço,email,celular,date,senha,crm,especialidade);
                arquivo.registrar(medico);
                LoginForm.medicosDb.add(medico);
                JOptionPane.showMessageDialog(null, "Conta criada com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                System.out.println("Sucesso");

                this.dispose();

            }
            else if (tipoContaCombo.getSelectedIndex() == 1){
                if(nBalcao.isEmpty()){
                    JOptionPane.showMessageDialog(null, "O número do balcão não foi preenchido", "Erro", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                int n = 0;
                try{
                    n = Integer.parseInt(nBalcao);
                }catch(NumberFormatException e){
                    JOptionPane.showMessageDialog(null, "Informe um número inteiro para o balcão", "Erro", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                Atendente atendente = new Atendente(n, nome, cpf, sexo, endereço, email, celular, date, senha);
                arquivo.registrar(atendente);
                LoginForm.atendentesDb.add(atendente);
                JOptionPane.showMessageDialog(null, "Conta criada com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                System.out.println("Sucesso");

                this.dispose();
            }
            else if (tipoContaCombo.getSelectedIndex() == -1)
                JOptionPane.showMessageDialog(null, "Você precisa selecionar um tipo de conta", "Erro", JOptionPane.ERROR_MESSAGE);


            arquivo.close();
        }
    }//GEN-LAST:event_criarContaBntActionPerformed

    private void senhaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhaFieldActionPerformed

    private void CloseLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseLblMouseClicked
        System.exit(0);
    }//GEN-LAST:event_CloseLblMouseClicked

    private void MinimizeLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeLblMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_MinimizeLblMouseClicked

    private void tipoContaComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoContaComboActionPerformed
        String value = tipoContaCombo.getSelectedItem().toString();
//        System.out.println("RegisterForm.java " + value);
        if (value.equals("Médico")){
            crmLbl.setVisible(true);
            crmTxtField.setVisible(true);
            especialidadeLbl.setVisible(true);
            especialidadeTxtField.setVisible(true);
            nBalcaoLbl.setVisible(false);
            nBalcaoTxtField.setVisible(false); 
        }
        else{
            crmLbl.setVisible(false);
            crmTxtField.setVisible(false);
            especialidadeLbl.setVisible(false);
            especialidadeTxtField.setVisible(false);
            nBalcaoLbl.setVisible(true);
            nBalcaoTxtField.setVisible(true);
        }
        
       
    }//GEN-LAST:event_tipoContaComboActionPerformed

    private void especialidadeTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_especialidadeTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_especialidadeTxtFieldActionPerformed

    private void nBalcaoTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nBalcaoTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nBalcaoTxtFieldActionPerformed

    private void dataNascimentoTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataNascimentoTxtFieldActionPerformed
    }//GEN-LAST:event_dataNascimentoTxtFieldActionPerformed

    private void cpfTxtField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfTxtField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpfTxtField1ActionPerformed

    private void crmTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crmTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crmTxtFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CloseLbl;
    private javax.swing.JLabel MinimizeLbl;
    private javax.swing.JButton cancelarBnt;
    private javax.swing.JLabel celularLbl;
    private javax.swing.JFormattedTextField celularTxtField;
    private javax.swing.JLabel cpfLbl;
    private javax.swing.JFormattedTextField cpfTxtField1;
    private javax.swing.JButton criarContaBnt;
    private javax.swing.JLabel crmLbl;
    private javax.swing.JTextField crmTxtField;
    private javax.swing.JLabel dataDeNascimentoLbl;
    private javax.swing.JFormattedTextField dataNascimentoTxtField;
    private javax.swing.JLabel emailLbl1;
    private javax.swing.JTextField emailTxtField;
    private javax.swing.JLabel endereçoLbl;
    private javax.swing.JTextField endereçoTxtField;
    private javax.swing.JLabel especialidadeLbl;
    private javax.swing.JTextField especialidadeTxtField;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel nBalcaoLbl;
    private javax.swing.JTextField nBalcaoTxtField;
    private javax.swing.JLabel nomeLbl;
    private javax.swing.JTextField nomeTxtField;
    private javax.swing.JPasswordField senhaField;
    private javax.swing.JLabel senhaLbl;
    private javax.swing.JComboBox<String> sexoCombo;
    private javax.swing.JLabel sexoLbl;
    private javax.swing.JComboBox<String> tipoContaCombo;
    private javax.swing.JLabel tipoDeContaLbl;
    // End of variables declaration//GEN-END:variables
}
